<?php

namespace App\Mcp\Tools\PlatformManagerTools\FlyCmsTools\WebsiteTools;

use App\Mcp\Support\McpAccess;
use App\Mcp\Tools\PlatformManagerTools\FlyCmsTools\FlyCmsTool;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Attributes\Description;

#[Description('A description of what this tool does.')]
class CreateWebsiteTool extends FlyCmsTool
{
    /**
     * Handle the tool request.
     */
    public function handle(Request $request): Response
    {
        $user = McpAccess::user($request);
        $channel = McpAccess::channel($user, $request->get('channel_id'));
        $this->validateChannel($channel);

        // TODO: ...

        return Response::text('The content generated by the tool.');
    }

    /**
     * Get the tool's input schema.
     *
     * @return array<string, JsonSchema>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'channel_id' => $schema->string()
                ->description('The ULID of the channel that belongs to a platform with type = flycms')
                ->required(),
        ];
    }
}
