apiVersion: v1
kind: Secret
metadata:
  name: firehub-secret
  namespace: {{ K8S_NAMESPACE }}
data:
  APP_KEY: "{{ APP_KEY }}"
  SENTRY_LARAVEL_DSN: "{{ SENTRY_LARAVEL_DSN }}"

  DB_CONNECTION: "pgsql"
  DB_HOST: "{{ DB_HOST }}"
  DB_PORT: "{{ DB_PORT }}"
  DB_DATABASE: "{{ DB_DATABASE }}"
  DB_USERNAME: "{{ DB_USERNAME }}"
  DB_PASSWORD: "{{ DB_PASSWORD }}"

  REDIS_HOST: "{{ REDIS_HOST }}"
  REDIS_USERNAME: "{{ REDIS_USERNAME }}"
  REDIS_PASSWORD: "{{ REDIS_PASSWORD }}"
  REDIS_PORT: "{{ REDIS_PORT }}"

  AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
  AWS_DEFAULT_REGION: "{{ AWS_DEFAULT_REGION }}"
  AWS_BUCKET: "{{ AWS_BUCKET }}"
  AWS_USE_PATH_STYLE_ENDPOINT: "{{ AWS_USE_PATH_STYLE_ENDPOINT }}"
  AWS_ENDPOINT: "{{ AWS_ENDPOINT }}"
