apiVersion: v1
kind: Secret
metadata:
  name: firehub-secret
  namespace: {{ K8S_NAMESPACE }}
data:
  APP_KEY: "{{ APP_KEY }}"
  SENTRY_LARAVEL_DSN: "{{ SENTRY_LARAVEL_DSN }}"

  DB_CONNECTION: "{{ DB_CONNECTION }}"
  DB_HOST: "{{ DB_HOST }}"
  DB_PORT: "{{ DB_PORT }}"
  DB_DATABASE: "{{ DB_DATABASE }}"
  DB_USERNAME: "{{ DB_USERNAME }}"
  DB_PASSWORD: "{{ DB_PASSWORD }}"
  MYSQL_ATTR_SSL_CA: "{{ MYSQL_ATTR_SSL_CA }}"

  PADDLE_SANDBOX: "{{ PADDLE_SANDBOX }}"
  PADDLE_CLIENT_SIDE_TOKEN: "{{ PADDLE_CLIENT_SIDE_TOKEN }}"
  PADDLE_API_KEY: "{{ PADDLE_API_KEY }}"
  PADDLE_WEBHOOK_SECRET: "{{ PADDLE_WEBHOOK_SECRET }}"

  REDIS_HOST: "{{ REDIS_HOST }}"
  REDIS_USERNAME: "{{ REDIS_USERNAME }}"
  REDIS_PASSWORD: "{{ REDIS_PASSWORD }}"
  REDIS_PORT: "{{ REDIS_PORT }}"

  MAIL_MAILER: "{{ MAIL_MAILER }}"
  MAIL_HOST: "{{ MAIL_HOST }}"
  MAIL_PORT: "{{ MAIL_PORT }}"
  MAIL_USERNAME: "{{ MAIL_USERNAME }}"
  MAIL_PASSWORD: "{{ MAIL_PASSWORD }}"
  MAIL_ENCRYPTION: "{{ MAIL_ENCRYPTION }}"
  MAIL_FROM_ADDRESS: "{{ MAIL_FROM_ADDRESS }}"
  MAIL_FROM_NAME: "{{ MAIL_FROM_NAME }}"

  RESEND_KEY: "{{ RESEND_KEY }}"

  AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
  AWS_DEFAULT_REGION: "{{ AWS_DEFAULT_REGION }}"

  DEFAULT_STORAGE_AWS_ACCESS_KEY_ID: "{{ DEFAULT_STORAGE_AWS_ACCESS_KEY_ID }}"
  DEFAULT_STORAGE_AWS_SECRET_ACCESS_KEY: "{{ DEFAULT_STORAGE_AWS_SECRET_ACCESS_KEY }}"
  DEFAULT_STORAGE_AWS_DEFAULT_REGION: "{{ DEFAULT_STORAGE_AWS_DEFAULT_REGION }}"
  DEFAULT_STORAGE_AWS_BUCKET: "{{ DEFAULT_STORAGE_AWS_BUCKET }}"
  DEFAULT_STORAGE_AWS_URL: "{{ DEFAULT_STORAGE_AWS_URL }}"
  DEFAULT_STORAGE_AWS_ENDPOINT: "{{ DEFAULT_STORAGE_AWS_ENDPOINT }}"
  DEFAULT_STORAGE_AWS_USE_PATH_STYLE_ENDPOINT: "{{ DEFAULT_STORAGE_AWS_USE_PATH_STYLE_ENDPOINT }}"

  ZENDESK_SUBDOMAIN: "{{ ZENDESK_SUBDOMAIN }}"
  ZENDESK_SHARED_SECRET: "{{ ZENDESK_SHARED_SECRET }}"
  ZENDESK_REDIRECT_URL: "{{ ZENDESK_REDIRECT_URL }}"
