[PHP]
post_max_size = 20M
upload_max_filesize = 20M
variables_order = EGPCS
pcov.directory = .
memory_limit = 256M
display_errors = Off
display_startup_errors = Off
log_errors = On
error_reporting = E_ALL
