# CLI Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firehub-cli-deployment
  namespace: {{ K8S_NAMESPACE }}
  labels:
    app: cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cli
  template:
    metadata:
      labels:
        app: cli
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: '{{ NODE_LABEL_SELECTOR_KEY }}'
                    operator: In
                    values:
                      - "{{ WORKER_DEPLOYMENT_NODE_LABEL_SELECTOR_VALUE }}"
      containers:
        - name: cli-container
          image: '{{ PHP_IMAGE }}'
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          command: [ "sleep" ]
          args: [ "infinity" ]
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: firehub-env
            - secretRef:
                name: firehub-secret
          resources:
            limits:
              cpu: '{{ WORKER_CPU_LIMIT }}'
              memory: '{{ WORKER_MEMORY_LIMIT }}'
            requests:
              cpu: '{{ WORKER_CPU_REQUEST }}'
              memory: '{{ WORKER_MEMORY_REQUEST }}'