# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firehub-ingress
  namespace: {{ K8S_NAMESPACE }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-hide-headers: "X-Powered-By"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ APP_HOST }}
      http:
        paths:

          # MCP Server path
          - pathType: Prefix
            path: '/mcp'
            backend:
              service:
                name: firehub-mcp-server-service
                port:
                  number: 80


          # Default path
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: firehub-web-service
                port:
                  number: 80
